### ISSUE TITLE
listAll in Folder options are required

### ISSUE THREAD

**Issue by arnacmj** [Files-com/files-sdk-php#4]
In the documentation, only the path is required, but when using this sdk it seems all are required!

**Comment by bombino** [comment]
Hi!  Thanks for the bug report.  We will be looking into this shortly!

**Comment by rommelsantor** [comment]
Hi, @arnacmj - 

Can you please provide a little more info? There is no `listAll()` method in the `Folder` class, just `listFor()`, which does function properly with just the `$path` parameter provided.

Thanks!
