### ISSUE TITLE
Error when getting file download - preview_size size must be of type string

### ISSUE THREAD

**Issue by josiahke** [Files-com/files-sdk-php#8]
![image (3)-21](https://github.com/Files-com/files-sdk-php/assets/8400694/5b45de3c-50f2-43ed-93b0-a3f4876b1910)

both
` $file->download();`
 and
` $file->download(['with_previews' => true,'preview_size' => 'small']);`
 
 return the above error 
 
 after the latest update
 
 
![image](https://github.com/Files-com/files-sdk-php/assets/8400694/99cd32a2-ade3-4399-b4d1-c19d6df0a34c)

**Comment by josiahke** [comment]
version 1.0.474 works well

![image](https://github.com/Files-com/files-sdk-php/assets/8400694/2ea73d2f-a773-4eb9-a4b8-357310f621bf)

**Comment by jlarmstrong** [comment]
We release version [v1.2.40](https://github.com/Files-com/files-sdk-php/releases/tag/v1.2.40) that resolves the reported issue.
